config/routes.rb
Rails.application.routes.draw do

  resources :pins
  root 'pins#index'
end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy]
	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end
	
	def new
		@pin = Pin.new
	end
	
	def create
		@pin = Pin.new(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Foi ;) "
		else
			render 'new'
		end
	end
	
	def edit
	end
	
	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Atualizado"
		else
			render 'edit'
		end
	end
	
	def destroy
		@pin.destroy
		redirect_to root_path
	end
	
	private
	def pin_params
		params.require(:pin).permit(:title, :desc)
	end
	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	- flash.each do |name, msg|
		= content_tag :div, msg, class: "alert alert-info"
	=yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true} do |f|
	- if @pin.errors.any?
		#errors
			%h2
			= pluralize(@pin.errors.count, "error")
			Dando ruim para salvar
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.input :title, input_html: { class: 'form-control'}
	.form-group
		= f.input :desc, input_html: { class: 'form-control'}
	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
%h1 Editar
= render 'form'
= link_to "Cancelar", pin_path

app/views/pins/index.html.haml
= link_to "Crie", new_pin_path
- @pins.each do |p|
	%h2= link_to p.title, p

app/views/pins/new.html.haml
%h1 Novo

= render 'form'
= link_to "Voltar", root_path

app/views/pins/show.html.haml
%h1= @pin.title
%p= @pin.desc

= link_to "Voltar", root_path
= link_to "Editar", edit_pin_path
= link_to "Excluir", pin_path, method: :delete, data: { confirm: "Vai excluir mesmo????"}